import { useEffect, useMemo, useRef, useState } from 'react';
import { UploadCloud, X, Image as ImageIcon, WandSparkles, AlertCircle, CheckCircle2, LockKeyhole, ArrowRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { analytics, uploadGeneration, wsUrl } from '../lib/api';
import { supabase } from '../lib/supabase';
import type { Bootstrap, Generation } from '../lib/types';
import AdSlot from '../components/AdSlot';
function UploadBox({label,subtitle,file,setFile,maxMb}:{label:string;subtitle:string;file:File|null;setFile:(f:File|null)=>void;maxMb:number}){const input=useRef<HTMLInputElement>(null);const preview=useMemo(()=>file?URL.createObjectURL(file):null,[file]);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);const pick=(f?:File)=>{if(!f)return;if(f.size>maxMb*1024*1024){alert(`Image must be ${maxMb} MB or smaller.`);return}if(!['image/jpeg','image/png','image/webp'].includes(f.type)){alert('Use JPG, PNG or WEBP.');return}setFile(f);analytics('image_upload_completed',{kind:label.toLowerCase()})};return <div className={`upload-box ${file?'has-file':''}`} onClick={()=>!file&&input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();pick(e.dataTransfer.files[0])}}>{file&&preview?<><img src={preview}/><button className="remove-file" onClick={e=>{e.stopPropagation();setFile(null)}}><X size={16}/></button><div className="file-meta"><CheckCircle2 size={16}/><span>{file.name}</span><small>{(file.size/1024/1024).toFixed(2)} MB</small></div></>:<><div className="upload-icon"><UploadCloud/></div><h3>{label}</h3><p>{subtitle}</p><span className="browse">Choose image</span><small>JPG, PNG or WEBP · max {maxMb} MB</small></>}<input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>pick(e.target.files?.[0])}/></div>}
export default function TryOn({bootstrap,refresh}:{bootstrap:Bootstrap|null;refresh:()=>void}){const nav=useNavigate();const [person,setPerson]=useState<File|null>(null),[garment,setGarment]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');const isPaid=!!bootstrap?.session.is_paid;const maxMb=Number(isPaid?bootstrap?.config.paid_max_upload_mb??10:bootstrap?.config.free_max_upload_mb??2);const remaining=bootstrap?.session.authenticated?bootstrap.session.credits:bootstrap?.session.guest_remaining??Number(bootstrap?.config.free_trial_generations??3);
const run=async()=>{if(!person||!garment)return;setBusy(true);setError('');setStatus('Preparing your images…');analytics('generation_started');try{const gen=await uploadGeneration(person,garment) as Generation;refresh();setStatus('Creating your look…');const {data}=await supabase.auth.getSession();const ws=new WebSocket(wsUrl(gen.id,data.session?.access_token));let finished=false;ws.onmessage=e=>{const payload=JSON.parse(e.data);const g=payload.generation as Generation;if(g.status==='processing')setStatus('AI is fitting the outfit…');if(g.status==='completed'){finished=true;analytics('generation_completed');ws.close();refresh();nav(`/result/${g.id}`)}if(g.status==='failed'){finished=true;setBusy(false);setError(g.safe_error_message||'Generation failed. Your credit will be handled safely.');analytics('generation_failed');ws.close();refresh()}};ws.onerror=()=>{if(!finished){setStatus('Still working — reconnecting safely…');setTimeout(()=>nav(`/result/${gen.id}`),1200)}}}catch(e){const er=e as Error & {code?:string};setBusy(false);setError(er.message);if(er.code==='FREE_TRIAL_EXHAUSTED')analytics('free_limit_reached')}};
return <section className="section-shell tryon-page"><div className="tryon-head"><div><div className="pill"><WandSparkles size={15}/> Virtual fitting room</div><h1>Create your<br/><em>new look.</em></h1></div><div className="trial-meter"><span>{bootstrap?.session.authenticated?'Credits':'Free tries'}</span><strong>{remaining}</strong><small>remaining</small></div></div>{!isPaid&&<AdSlot slug="tryon_top"/>}<div className="upload-grid"><UploadBox label="Your photo" subtitle="A clear photo of you, ideally facing forward." file={person} setFile={setPerson} maxMb={maxMb}/><div className="upload-join">+</div><UploadBox label="Your outfit" subtitle="The clothing item or complete look you want to try." file={garment} setFile={setGarment} maxMb={maxMb}/></div><div className="tryon-action"><div className="privacy-line"><LockKeyhole size={16}/><span>Your uploads are private and processed securely.</span></div><button className="button large generate-btn" disabled={!person||!garment||busy} onClick={run}>{busy?<><span className="spinner"/>{status}</>:<>Generate my look <WandSparkles size={18}/></>}</button>{error&&<div className="error-box"><AlertCircle size={18}/><span>{error}</span></div>}</div>{busy&&!isPaid&&<AdSlot slug="generation_loading_primary" className="loading-ad"/>}{Number(remaining)<=1&&!isPaid&&<div className="upgrade-nudge"><div><p className="eyebrow">Almost out of free tries</p><h3>Keep creating from our current credit pricing.</h3></div><button className="button secondary" onClick={()=>nav('/pricing')}>See pricing <ArrowRight size={17}/></button></div>}</section>}
